# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-04 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='orderd_by',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='orderd_product',
            new_name='product',
        ),
    ]
