# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-26 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('brand', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(choices=[('U', 'Unisex'), ('M', 'Male'), ('F', 'Female')], default='U', max_length=5)),
                ('volume', models.IntegerField(choices=[('Vol', 25), ('Vol', 30), ('Vol', 40), ('Vol', 50), ('Vol', 65), ('Vol', 70), ('Vol', 90), ('Vol', 100), ('Vol', 125), ('Vol', 130), ('Vol', 150), ('Vol', 175), ('Vol', 200), ('Vol', 300)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('created', models.DateField()),
            ],
        ),
    ]
