# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPerfume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('score', models.IntegerField(verbose_name=(1, 2, 3, 4))),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(default='', max_length=40)),
                ('gender', models.CharField(choices=[('unisex', 'unisex'), ('male', 'male'), ('female', 'female')], default='unisex', max_length=7)),
                ('volume', models.CharField(choices=[('25', 25), ('30', 30), ('40', 40), ('50', 50), ('65', 65), ('70', 70), ('90', 90), ('100', 100), ('125', 125), ('130', 130), ('150', 150), ('175', 175), ('200', 200), ('300', 300)], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/product_image')),
                ('created', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='commentperfume',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='products.Perfume'),
        ),
    ]
