# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-26 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200226_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='volume',
            field=models.CharField(choices=[('25', 25), ('30', 30), ('40', 40), ('50', 50), ('65', 65), ('70', 70), ('90', 90), ('100', 100), ('125', 125), ('130', 130), ('150', 150), ('175', 175), ('200', 200), ('300', 300)], max_length=5),
        ),
    ]
