# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-05 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200305_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentperfume',
            name='score',
            field=models.IntegerField(verbose_name=(1, 2, 3, 4)),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(upload_to='images/product_image'),
        ),
    ]
